// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGYeBVxr3ouzcQCbTHJQsgTsW2UDPX9FI',
    appId: '1:995511644780:web:4131fddd21c82a8c871e49',
    messagingSenderId: '995511644780',
    projectId: 'h2o-project-e83d9',
    authDomain: 'h2o-project-e83d9.firebaseapp.com',
    databaseURL: 'https://h2o-project-e83d9-default-rtdb.firebaseio.com',
    storageBucket: 'h2o-project-e83d9.firebasestorage.app',
    measurementId: 'G-LXJNFV1E5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiLkat5aIx7cHba4b0OwTOBrQveN2TduM',
    appId: '1:995511644780:android:c6a7ee4f3e292277871e49',
    messagingSenderId: '995511644780',
    projectId: 'h2o-project-e83d9',
    databaseURL: 'https://h2o-project-e83d9-default-rtdb.firebaseio.com',
    storageBucket: 'h2o-project-e83d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA45Yd3JfV9zwiKNUVvMegK5l_p50Zkltk',
    appId: '1:995511644780:ios:c55ea165cd2a0555871e49',
    messagingSenderId: '995511644780',
    projectId: 'h2o-project-e83d9',
    databaseURL: 'https://h2o-project-e83d9-default-rtdb.firebaseio.com',
    storageBucket: 'h2o-project-e83d9.firebasestorage.app',
    iosBundleId: 'com.example.h2oPlc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA45Yd3JfV9zwiKNUVvMegK5l_p50Zkltk',
    appId: '1:995511644780:ios:c55ea165cd2a0555871e49',
    messagingSenderId: '995511644780',
    projectId: 'h2o-project-e83d9',
    databaseURL: 'https://h2o-project-e83d9-default-rtdb.firebaseio.com',
    storageBucket: 'h2o-project-e83d9.firebasestorage.app',
    iosBundleId: 'com.example.h2oPlc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGYeBVxr3ouzcQCbTHJQsgTsW2UDPX9FI',
    appId: '1:995511644780:web:099168d194303ca4871e49',
    messagingSenderId: '995511644780',
    projectId: 'h2o-project-e83d9',
    authDomain: 'h2o-project-e83d9.firebaseapp.com',
    databaseURL: 'https://h2o-project-e83d9-default-rtdb.firebaseio.com',
    storageBucket: 'h2o-project-e83d9.firebasestorage.app',
    measurementId: 'G-8T65BY0DYE',
  );
}
